config/routes.rb
Rails.application.routes.draw do
  get 'project-examples', to: 'pages#project_examples'
  get 'contact', to: 'pages#contact'

  resource :contact, only: [:create], controller: 'contact'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def create
    redirect_to(root_path, alert: "You have already sent a contact message") if current_contact
    ContactMailer.with(contact_email: params[:email], contact_message: params[:message], first_name: params[:first_name], last_name: params[:last_name]).deliver_later
    session[:contact_email] = params[:email]
    redirect_to root_path, notice: "Your message was sent. I will be in touch shortly"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def project_examples; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_contact
    @contact ||= session[:contact_email]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact/_contact_form.html.erb
<h3 class="text-3xl text-gray-300 mb-4 text-center"> Contact me </h3>
<p class="text-xl text-gray-300 mb-4 text-center"> Send me a message and start the conversation </p>
<%= form_with url: contact_path do |form| %>
  <div class="flex justify-between mb-4">
    <div class="flex flex-col w-2/5">
      <%= form.label :first_name, class: "text-gray-200" %>
      <%= form.text_field :first_name %>
    </div>
    <div class="flex flex-col w-3/5 ml-4">
      <%= form.label :last_name, class: "text-gray-200" %>
      <%= form.text_field :last_name %>
    </div>
  </div>
  <div class="flex flex-col">
    <%= form.label :email, class: "text-gray-200" %>
    <%= form.email_field :email %>
  </div>
  <div class="flex flex-col mt-4">
    <%= form.label :message, class: "text-gray-200" %>
    <%= form.text_area :message, class:"h-40", style: "resize: none;", value: "Hey Enoch I want to contact you about something" %>
  </div>
  <div class="mt-4">
    <%= form.submit "send message", class: "bg-green-500 text-green-50 p-2 rounded-lg cursor-pointer text-lg" %>
  </div>
<% end %>

app/views/home/_additional_skills.html.erb
<div class="h-[35vh]">
  <h3 class="text-3xl mt-32 text-gray-200 text-center">
    Additional Skills
  </h3>

  <div class="flex flex-wrap justify-around max-w-xl w-full mx-auto mt-10">
    <div class="flex justify-center items-center">
      <span class="rounded-lg bg-gray-300 h-10 w-32 text-gray-900 p-1 mb-6">
        AWS
      </span>
    </div>
    <div class="flex justify-center items-center">
      <span class="rounded-lg h-10 w-32 p-1 bg-gray-300 text-gray-900 mb-6">
        SQL
      </span>
    </div>
    <div class="flex justify-center items-center">
      <span class="rounded-lg h-10 p-1 bg-gray-300 text-gray-900 whitespace-nowrap mb-6">
        Automated Testing
      </span>
    </div>
    <div class="flex justify-center items-center">
      <span class="rounded-lg w-32 h-10 p-1 bg-gray-300 text-gray-900 mb-6">
        Websockets
      </span>
    </div>
    <div class="flex justify-center items-center">
      <span class="rounded-lg w-32 h-10 p-1 bg-gray-300 text-gray-900 mb-6">
        Linux
      </span>
    </div>
  </div>
</div>

app/views/home/_contact_form.html.erb
<h3 class="text-3xl text-gray-300 mb-4 text-center"> Contact me </h3>
<p class="text-xl text-gray-300 mb-4 text-center"> Send me a message and start the conversation </p>
<%= form_with url: "" do |form| %>
  <div class="flex justify-between mb-4">
    <div class="flex flex-col w-2/5">
      <%= form.label :first_name, class: "text-gray-200" %>
      <%= form.text_field :first_name %>
    </div>
    <div class="flex flex-col w-3/5 ml-4">
      <%= form.label :last_name, class: "text-gray-200" %>
      <%= form.text_field :last_name %>
    </div>
  </div>
  <div class="flex flex-col">
    <%= form.label :email, class: "text-gray-200" %>
    <%= form.email_field :email %>
  </div>
  <div class="flex flex-col mt-4">
    <%= form.label :message, class: "text-gray-200" %>
    <%= form.text_area :message, class:"h-40", style: "resize: none;", value: "Hey Enoch I want to contact you about something" %>
  </div>
  <div class="mt-4">
    <%= form.submit "send message", class: "bg-green-500 text-green-50 p-2 rounded-lg cursor-pointer text-lg" %>
  </div>
<% end %>

app/views/home/_css_frameworks.html.erb
<div class="h-[20vh]">
  <h3 class="text-3xl mt-20 text-gray-200 text-center">
    CSS Frameworks
  </h3>

  <div class="flex flex-wrap justify-around max-w-xl w-full mx-auto mt-10">
    <div class="flex justify-center items-center">
      <span class="rounded-lg w-32 h-10 p-1 bg-gray-300 text-gray-900">
        Tailwindcss
      </span>
    </div>
    <div class="flex justify-center items-center">
      <span class="rounded-lg w-32 h-10 p-1 bg-gray-300 text-gray-900">
        Bootstrap
      </span>
    </div>
  </div>
</div>

app/views/home/_javascript_frameworks.html.erb
<div class="h-[40vh]">
  <h3 class="text-3xl mt-20 text-gray-200 text-center">
    Javascript Frameworks
  </h3>

  <div class="flex flex-wrap justify-around max-w-xl w-full mx-auto mt-10">
    <div class="flex justify-center items-center">
      <span class="rounded-lg w-32 p-1 h-10 bg-gray-300 text-gray-900">
        Hotwire
      </span>
    </div>
    <div class="flex justify-center items-center">
      <span class="rounded-lg w-32 p-1 h-10 bg-gray-300 text-gray-900">
        StimulusJs
      </span>
    </div>
    <div class="flex justify-center items-center">
      <span class="rounded-lg w-32 p-1 h-10 bg-gray-300 text-gray-900">
        ReactJs
      </span>
    </div>
  </div>
</div>

app/views/home/_main_skills.html.erb
<div class="flex flex-col justify-center">
  <h2 class="text-4xl text-center text-gray-200"> Main Skills </h2>

  <div class="mt-14 w-full grid md:grid-cols-2 xl:grid-cols-4 gap-4">
    <div class="w-full group">
      <a href="#" class=" flex flex-col items-center ">
        <span class="text-gray-200 text-lg font-semibold mb-6"> Ruby On Rails </span>
        <%= image_tag "circle-rails.png", class: "object-cover w-32 group-hover:bg-blue-500 rounded-full p-0.5" %>
      </a>
    </div>
    <div class="w-full group">
      <a href="#" class=" flex flex-col items-center ">
        <span class="text-gray-200 text-lg font-semibold"> Javascript </span>
        <%= image_tag "circle-js.png", class: "object-cover w-40 group-hover:bg-blue-500 rounded-full p-0.5" %>
      </a>
    </div>
    <div class="w-full group">
      <a href="#" class=" flex flex-col items-center ">
        <span class="text-gray-200 text-lg mb-4 font-semibold"> HTML </span>
        <%= image_tag "circle-html.png", class: "object-cover w-32 group-hover:bg-blue-500 rounded-full p-0.5" %>
      </a>
    </div>
    <div class="w-full group">
      <a href="#" class=" flex flex-col items-center ">
        <span class="text-gray-200 text-lg mb-2 font-semibold"> CSS </span>
        <%= image_tag "circle-css.png", class: "object-cover w-36 group-hover:bg-blue-500 rounded-full p-0.5" %>
      </a>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="w-full min-h-screen bg-gray-800 pb-36">
  <div class="min-h-[80vh] bg-gradient-to-r from-indigo-500 to-indigo-700 pt-40">
    <h1 class="font-bold text-6xl text-gray-200 text-center">Enoch Tamulonis </h1>
    <p class="text-xl text-gray-100 text-center mt-8 max-w-sm lg:max-w-xl mx-auto">
      Web Developer creating beautiful experiences and helping businesses succeed!
    </p>
    <div class="mt-36 max-w-4xl w-full mx-auto px-4">
      <a href="contact" class="text-2xl text-gray-200 border-b border-indigo-200 hover:border-indigo-400"> Contact Me </a>
       <a href="project-examples" class="text-2xl text-gray-200 ml-5 border-b border-indigo-200 hover:border-indigo-400"> Projects Showcase </a>
    </div>
  </div>
  <div class="min-h-screen w-full relative">
    <div class="absolute -top-10 w-full">
      <div class="grid gap-16 lg:gap-0 lg:grid-cols-3 max-w-7xl w-full mx-auto">
        <div class="max-w-sm w-full h-56 bg-gray-900 shadow-sm shadow-indigo-500 rounded-sm flex flex-col justify-center items-center mx-auto">
          <span class='text-2xl text-gray-100 mt-4'> 
            Web Development
          </span>
          <%= inline_svg_tag("desktop-computer", class: 'w-14 text-gray-200 mt-4') %>
        </div>
        <div class="max-w-sm w-full h-56 bg-gray-900 shadow-sm shadow-indigo-500 rounded-sm flex flex-col justify-center items-center mx-auto">
          <span class='text-2xl text-gray-100 mt-4'> 
            Mobile Development
          </span>
          <%= inline_svg_tag("smartphone", class: 'w-14 text-gray-200 mt-4') %>
        </div>
        <div class="max-w-sm w-full h-56 bg-gray-900 shadow-sm shadow-indigo-500 rounded-sm flex flex-col justify-center items-center mx-auto">
          <span class='text-2xl text-gray-100 mt-4'> 
            Site Management
          </span>
          <%= inline_svg_tag("adjustments", class: 'w-14 text-gray-200 mt-4') %>
        </div>
      </div>
      <div class="mt-16 max-w-7xl w-full mx-auto">
        <h3 class="text-2xl text-gray-100 text-center"> You can also find me on these platforms </h3>
        <div class="flex flex-col items-center">
          <%= link_to "Linkedin", "https://www.linkedin.com/in/enoch-tamulonis/", class: "text-xl text-gray-200 mt-6 hover:underline" %>
          <%= link_to "Youtube", "https://www.youtube.com/channel/UCTqRqI5w_uB10Z-IBT-A_gA", class: "text-xl text-gray-200 mt-6 hover:underline" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="fixed top-0 h-8 w-full px-8 py-3">
  <div class="flex w-full">
    <%= link_to root_path, class: 'p-3 rounded-full hover:bg-gray-600 transition duration-200' do %>
      <%= inline_svg_tag('home', class: 'w-8 text-gray-200') %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Enoch Tamulonis </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <% if Rails.env.development? %>
      <%= javascript_include_tag "hotwire-livereload", defer: true %>
    <% end %>
  </head>

  <body class="bg-gray-800">
    <%= render 'layouts/navbar' unless controller_path == 'home' %>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="max-w-5xl w-full mx-auto mt-36 rounded-sm px-4">
  <h1 class="text-3xl text-gray-300 text-center"> Contact Me </h1>
  <div class="max-w-3xl w-full mx-auto flex justify-between mt-6">
    <div class="grid gap-2">
      <label class="text-xl text-gray-100"> Email </label>
      <p class="text-xl text-gray-200"> enochtamulonis@gmail.com </p>
    </div>
    <div class="grid gap-2">
      <label class="text-xl text-gray-100"> Phone </label>
      <p class="text-xl text-gray-200"> 407-516-5884 </p>
    </div>
  </div>
</div>

app/views/pages/project_examples.html.erb
<div class="h-[40vh] w-full bg-indigo-500 flex items-center justify-center">
  <h1 class="text-4xl md:text-6xl font-semibold text-indigo-200 text-center"> Project Showcase </h1>
</div>
<div class="min-h-screen w-full relative">
  <div class="absolute -top-10 w-full">
    <div class="grid gap-16 lg:gap-0 lg:grid-cols-3 max-w-7xl w-full mx-auto">
      <%= link_to "https://www.wavclouds.com", class: "hover:-translate-y-1 transition-all duration-250 mx-auto", target: "_new" do %>
        <div class="max-w-sm w-full h-56 bg-gray-600 rounded-sm border-2 border-blue-200">
          <%= image_tag "wavclouds-site", class: "w-full h-full object-cover" %>
        </div>
        <div class="flex flex-col items-center mt-3">
          <span class="text-2xl text-blue-100"> Wavclouds </span>
          <p class="text-gray-200">
            Music licensing and streaming platform
          </p>
        </div>
      <% end %>

      <%= link_to "https://www.tapinspect.com", class: "hover:-translate-y-1 transition-all duration-250 mx-auto", target: "_new" do %>
        <div class="max-w-sm w-full h-56 bg-gray-600 rounded-sm border-2 border-blue-200">
          <%= image_tag "tapinspect-site", class: "w-full h-full object-cover" %>
        </div>
        <div class="flex flex-col items-center mt-3">
          <span class="text-2xl text-blue-100"> Tap Inspect </span>
          <p class="text-gray-200">
            Home inspection mobile app
          </p>
        </div>
      <% end %>

      <%= link_to "https://4beautymedspa.com/", class: "hover:-translate-y-1 transition-all duration-250 mx-auto", target: "_new" do %>
        <div class="max-w-sm w-full h-56 bg-gray-600 rounded-sm border-2 border-blue-200">
          <%= image_tag "4beauty-site", class: "w-full h-full object-cover" %>
        </div>
        <div class="flex flex-col items-center mt-3">
          <span class="text-2xl text-blue-100"> 4Beauty </span>
          <p class="text-gray-200">
            Plastic Surgery CRM
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>